language: csharp
solution: ./Backend/Sppd.TeamTuner.sln
mono: latest
dist: xenial
dotnet: 2.2

script:
- ./build.sh --target Run-All-Tests
- ./build.sh --target Upload-Coverage --Verbosity Diagnostic
